version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - tmaquize-prod

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - tmaquize-prod

  admin:
    build:
      context: ./backend
      dockerfile: Dockerfile.admin
    ports:
      - "8001:8001"
    networks:
      - tmaquize-prod


networks:
  tmaquize-prod: