"""empty message

Revision ID: 52ba67fa0e1c
Revises: fae97372adb9
Create Date: 2025-06-13 22:05:18.824405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ba67fa0e1c'
down_revision: Union[str, None] = 'fae97372adb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('total_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_score')
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
